import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { getShiurSkipSeconds, useListener, type ListenerRecording } from '@/components/listener-provider';
import { loadListenerRecordings } from '@/lib/public-recordings';

type Playlist = { id: string; name: string; recordingIds: string[] };
export default function PlaylistsScreen() {
  const { playlists, createPlaylist, renamePlaylist, deletePlaylist, addToPlaylist, removeFromPlaylist, reorderPlaylist, playAll } = useListener();
  const [recordings, setRecordings] = useState<ListenerRecording[]>([]);
  const [name, setName] = useState('');
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => {
    setError(null);
    loadListenerRecordings().then(setRecordings).catch(() => setError('Recordings are unavailable right now. Try again when the Torat Tsion library is reachable.'));
  }, []);
  useEffect(() => { void load(); }, [load]);
  const create = () => { createPlaylist(name); setName(''); };
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Text style={styles.eyebrow}>YOUR LIBRARY</Text><Text style={styles.title}>Playlists</Text><View style={styles.create}><TextInput onChangeText={setName} onSubmitEditing={create} placeholder="New playlist name" placeholderTextColor="#69717B" style={styles.input} value={name} /><Pressable onPress={create} style={styles.primary}><Text style={styles.primaryText}>Create</Text></Pressable></View>{error ? <View style={styles.errorPanel}><Text style={styles.error}>{error}</Text><Pressable onPress={load} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable></View> : playlists.map((playlist) => <PlaylistEditor key={playlist.id} playlist={playlist} recordings={recordings} onRename={renamePlaylist} onDelete={deletePlaylist} onAdd={addToPlaylist} onRemove={removeFromPlaylist} onReorder={reorderPlaylist} onPlay={() => playAll(recordings.filter((recording) => playlist.recordingIds.includes(recording.id)))} />)}</ScrollView></SafeAreaView>;
}
function PlaylistEditor({ playlist, recordings, onRename, onDelete, onAdd, onRemove, onReorder, onPlay }: { playlist: Playlist; recordings: ListenerRecording[]; onRename: (id: string, name: string) => void; onDelete: (id: string) => void; onAdd: (playlistId: string, recordingId: string) => void; onRemove: (playlistId: string, recordingId: string) => void; onReorder: (playlistId: string, recordingIds: string[]) => void; onPlay: () => void }) { const { activeRecording, player, play, status } = useListener(); const selected = playlist.recordingIds.map((id) => recordings.find((recording) => recording.id === id)).filter((recording): recording is ListenerRecording => Boolean(recording)); const move = (index: number, direction: -1 | 1) => { const next = index + direction; if (next < 0 || next >= playlist.recordingIds.length) return; const ids = [...playlist.recordingIds]; [ids[index], ids[next]] = [ids[next], ids[index]]; onReorder(playlist.id, ids); }; return <View style={styles.playlist}><View style={styles.playlistHeader}><TextInput defaultValue={playlist.name} onEndEditing={(event) => onRename(playlist.id, event.nativeEvent.text)} style={styles.playlistName} /><Pressable onPress={onPlay} style={styles.play}><Text style={styles.playText}>Play All</Text></Pressable><Pressable onPress={() => Alert.alert('Delete playlist?', playlist.name, [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: () => onDelete(playlist.id) }])}><Text style={styles.delete}>Delete</Text></Pressable></View>{selected.map((recording, index) => { const skipSeconds = getShiurSkipSeconds(recording); const active = activeRecording?.id === recording.id; return <View key={recording.id} style={styles.item}><Text style={styles.itemText} numberOfLines={1}>{recording.title}</Text>{skipSeconds !== null && <Pressable onPress={() => { if (active) { player.seekTo(skipSeconds); if (!status.playing) player.play(); } else play(recording, selected, skipSeconds); }}><Text style={styles.skip}>Skip to Shiur</Text></Pressable>}<Pressable onPress={() => move(index, -1)}><Text style={styles.action}>↑</Text></Pressable><Pressable onPress={() => move(index, 1)}><Text style={styles.action}>↓</Text></Pressable><Pressable onPress={() => onRemove(playlist.id, recording.id)}><Text style={styles.delete}>Remove</Text></Pressable></View>; })}{recordings.filter((recording) => !playlist.recordingIds.includes(recording.id)).slice(0, 8).map((recording) => <Pressable key={recording.id} onPress={() => onAdd(playlist.id, recording.id)} style={styles.add}><Text style={styles.addText}>+ {recording.title}</Text></Pressable>)}</View>; }
const styles = StyleSheet.create({ safe: { backgroundColor: '#f4f8ff', flex: 1 }, container: { padding: 22, paddingBottom: 130 }, eyebrow: { color: '#2d6cdf', fontSize: 10, fontWeight: '800', letterSpacing: 1.5 }, title: { color: '#142950', fontSize: 30, fontWeight: '700', marginTop: 7 }, create: { flexDirection: 'row', gap: 8, marginTop: 18 }, input: { backgroundColor: '#ffffff', borderColor: '#dfeaf7', borderRadius: 8, borderWidth: 1, color: '#142950', flex: 1, minHeight: 46, paddingHorizontal: 12 }, primary: { alignItems: 'center', backgroundColor: '#2d6cdf', borderRadius: 8, justifyContent: 'center', paddingHorizontal: 16 }, primaryText: { color: '#ffffff', fontWeight: '800' }, errorPanel: { backgroundColor: '#ffffff', borderColor: '#bfd4ff', borderRadius: 12, borderWidth: 1, marginTop: 18, padding: 16 }, error: { color: '#8f2d2d', lineHeight: 20 }, retry: { alignSelf: 'flex-start', backgroundColor: '#2d6cdf', borderRadius: 8, marginTop: 12, paddingHorizontal: 12, paddingVertical: 9 }, retryText: { color: '#ffffff', fontWeight: '800' }, playlist: { backgroundColor: '#ffffff', borderColor: '#dfeaf7', borderRadius: 10, borderWidth: 1, marginTop: 18, padding: 14 }, playlistHeader: { alignItems: 'center', flexDirection: 'row', gap: 8 }, playlistName: { color: '#142950', flex: 1, fontSize: 16, fontWeight: '700' }, play: { backgroundColor: '#2d6cdf', borderRadius: 6, paddingHorizontal: 9, paddingVertical: 8 }, playText: { color: '#ffffff', fontSize: 11, fontWeight: '800' }, delete: { color: '#b23a3a', fontSize: 11, fontWeight: '700' }, item: { alignItems: 'center', borderTopColor: '#dfeaf7', borderTopWidth: 1, flexDirection: 'row', gap: 8, marginTop: 12, paddingTop: 12 }, itemText: { color: '#142950', flex: 1, fontSize: 12 }, skip: { color: '#1d4ea8', fontSize: 10, fontWeight: '800' }, action: { color: '#2d6cdf', fontSize: 18, fontWeight: '700' }, add: { borderTopColor: '#dfeaf7', borderTopWidth: 1, marginTop: 10, paddingTop: 10 }, addText: { color: '#5b6e8d', fontSize: 12 } });
